### ISSUE TITLE
Get-InstalledSoftware: Computername = System.string[] after Export-csv 

### ISSUE THREAD

**Issue by artarik** [ThePoShWolf/Utilities#1]
after executing command :
`'PC1','PC2' | Get-InstalledSoftware | export-csv -LiteralPath C:\temp\test_installdeAPPs.csv -Delimiter "``t" -Encoding "UTF32" -NotypeInformation True -Force`
i have "System.String[]"  values in "ComputerName" column.
![Screenshot_1](https://user-images.githubusercontent.com/14920717/72899195-86f5b780-3d36-11ea-96b5-519e17c98d19.png)

To fix it i add `-join ""`  after `"ComputerName" = $Name`
It work for me but may be you can to suggest another way

**Comment by ThePoShWolf** [comment]
Hey, thanks I'll take a look! I didn't get a notification for this, so sorry for the sluggish response.

**Comment by artarik** [comment]
fix it by replace `"ComputerName" = $Name` on `"ComputerName" = [String]::Join("", $Name)`
