### ISSUE TITLE
Get-InstalledSoftware: mandatory is not necessary

### ISSUE THREAD

**Issue by LaurentLienhard** [ThePoShWolf/Utilities#2]
When you call just Get-InstalledSoftware without parameter it is supposed to take $env: computername but because of the mandatory=$True it asks to enter a parameter 
![image](https://user-images.githubusercontent.com/22775196/74413479-c5ffc000-4e3f-11ea-874e-e9f780e2b0d0.png)

just replace de mandatory=$true by $false

**Comment by ThePoShWolf** [comment]
You fixed this, thank you! I apparently don't have notifications set up, so sorry for the sluggish response.
